matrix:
  fast_finish: true
  include:
    - os: linux
      language: erlang
      otp_release: 20.1

# Avoid rebuilding Dialyzer PLT every time.
cache:
  directories:
     - "$HOME/.cache/rebar3"

script:
  - rebar3 do xref, dialyzer, eunit, ct, cover
  - rebar3 as lint lint
  - erl -noshell -eval "erl_tidy:dir("apps", [{test, true}])." -s init stop
  - sh scripts/cohort_test.sh
  - sh scripts/coverage_check.sh
  - rebar3 as prod do version, tree, tar
