language: erlang

# Avoid rebuilding Dialyzer PLT every time.
cache:
  directories:
     - "$HOME/.cache/rebar3"

script:
  - rebar3 do version, tree, dialyzer, xref, eunit, ct, cover
  - rebar3 as lint lint
  - sh scripts/coverage_check.sh
