matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      language: erlang
      otp_release: 21.0.2

# Avoid rebuilding Dialyzer PLT every time.
cache:
  directories:
     - "$HOME/.cache/rebar3"

script:
  - rebar3 do version, tree, xref, dialyzer, eunit, ct, cover
  - rebar3 as lint lint
  - erl -noshell -eval "erl_tidy:dir("apps", [{test, true}])." -s init stop
  - sh scripts/coverage_check.sh
  - rebar3 as prod,magnumopus do release
  - rebar3 as prod,obsequilis do release
  - sh scripts/cohort_test.sh

