matrix:
  fast_finish: true
  include:
    - os: linux
      language: erlang
      otp_release: 20.0

# Avoid rebuilding Dialyzer PLT every time.
cache:
  directories:
     - "$HOME/.cache/rebar3"

# Travis uses rebar by default. Get rebar3 instead.
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3

script:
  - escript rebar3 do version, tree, xref, dialyzer, eunit, ct, cover
  - escript rebar3 as lint lint
  - sh scripts/cohort_test.sh
  - sh scripts/coverage_check.sh
